name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
    - name: Build the Docker image
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
      run: docker build . --file Dockerfile --tag $DOCKER_REGISTRY:$RELEASE_VERSION
    - name: Docker Push
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
      run: docker push $DOCKER_REGISTRY:$RELEASE_VERSION

